# Generated by Django 3.2.6 on 2021-09-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_add_user_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todouser',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='todouser',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
